services:
  - type: web
    name: app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""  # Leave empty or use the default
    startCommand: uvicorn main:app --host 0.0.0.0 --port 80
    envVars:
      - key: CARGO_HOME
        value: /app/.cargo
      - key: CARGO_TARGET_DIR
        value: /app/target
