services:
  - type: web
    name: app
    env: python
    dockerfilePath: ./Dockerfile  # Ensure the Dockerfile path is correctly specified
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 80
    envVars:
      - key: CARGO_HOME
        value: /app/.cargo
      - key: CARGO_TARGET_DIR
        value: /app/target
